FROM ghcr.io/graalvm/native-image-community:21-ol9 AS build
WORKDIR /app
RUN microdnf install maven --setopt=install_weak_deps=0
COPY pom.xml .
RUN mvn dependency:go-offline
COPY . .
RUN mvn package -Pnative native:compile

FROM oraclelinux:9-slim
WORKDIR /app
COPY --from=build /app/target/vthreads .
ENTRYPOINT ["./vthreads"]